### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by cpellet** [Tommrodrigues/WiFiCrack#1]
Should rename the file wifi_disconnector.sh because that's all it does
![image](https://user-images.githubusercontent.com/18552249/63437579-1535dc80-c42b-11e9-9b7e-e7774e15a9b1.png)

**Comment by phenotypic** [comment]
The script works fine for me. Can you verify which version of macOS you are using?

**Comment by cpellet** [comment]
I'm using MacOS 10.15, thanks for your reply

**Comment by phenotypic** [comment]
It's entirely possible that the script no longer works as intended in macOS Catalina either as a result of a change in the `bash` version being used or a bug in the most recent betas. Unfortunately, I have been unable to test the script with the newest versions of macOS as I'm still on Mojave but will be sure to when the public release happens later this year.

In the meantime, feel free to fiddle with the script. As the error shows, the problem seems to be a simple syntax error, so adjusting line `190` may fix the problem.

**Comment by phenotypic** [comment]
Hi there. I've been able to successfully test the script with the most recent version of macOS Catalina (10.15.1) and have not run into the same issue as you.

Would you be able to try again on the newest version of macOS? If the issue persists, I think it could be a result of the newly implemented `zsh` shell. If you are using the `zsh` shell, try switching back to `bash` to see if that solves your problem.

**Comment by JasonLeeH** [comment]
I'm getting the same error btw

**Comment by Sepuka** [comment]
Are you sure that the app works? I see only "[*] Captured beacon frame, waiting for handshake..." all the time.
I run it it under zsh and under bash, I have MacOs 12.1
While it running I turn off my phone and turn on after that in order to make handshake it. how I can debug it?

**Comment by phenotypic** [comment]
Hi @Sepuka, unfortunately I no longer actively maintain this project so I can only offer limited guidance.

As the message says, the script is waiting for a handshake to be captured using the command on line `247`. If you would like to debug the sniffing stage manually, read through [this](https://louisabraham.github.io/articles/WPA-wifi-cracking-MBP.html) blog post which goes through the capturing process step-by-step.

Either way, I would recommend checking out [WiFiCrackPy](https://github.com/phenotypic/WiFiCrackPy) which I developed as the successor to this project. The new script is much more streamlined and does not capture handshakes in the same way.
